services:
  - type: web
    name: near-intents-swap-api
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start:server
    plan: starter
    numInstances: 1
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    disk:
      name: near-intents-storage
      mountPath: /tmp
      sizeGB: 1